# GLOBAL VARIABLES


s = 2  # NUMBER OF TUPLES TO SHOW
d = 2  # NUMBER OF ATTRIBUTES TO SHOW


H_INITIAL_UPPER_BOUND = 300  # THE INTIAL UPPER BOUND FOR H


LOWEST_DEGREE = 1  # THE LOWEST DEGREE OF POWER THE POLYNOMIAL FUNCTION HAS
HIGHEST_DEGREE = 10  # THE LOWEST DEGREE OF POWER THE POLYNOMIAL FUNCTION HAS


TIMES = 10000  # THE NUMBER OF TIMES WE WANT THE SIMULATION TO RUN


ITER_PER_ROUND = 5  # THE NUMBER OF QUESTIONS THE USER ANSWERS PER ROUND
